project:
  type: website
  output-dir: docs

  

website:
  favicon: images\me.jpg
  title: "Reza Hakimazar"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: pages\cv.qmd
        text: CV
        icon: file-earmark-person
      - href: pages\podcast.qmd
        text: Podcast
        icon: mic-fill

format:
  html:
    theme: minty
    fontsize: 1rem
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

