project:
  type: website
  output-dir: docs
website:
  favicon: images\me.png
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "The Jotter Pen"
        href: pages/blog.qmd
      - text: "Professional Snapshot"
        href: pages/cv.qmd
      - text: "Podcast (in Persian)"
        href: pages/podcast.qmd
  page-footer:
    right: "Built with {{<fa heart>}} and [Quarto](http://quarto.org)"
format:
  html:
    theme: flatly
    linkcolor: "#529E53"
    fontsize: 1rem
    toc: false

editor: visual


git remote add origin https://github.com/rezahakimazar/rezahakimazar.github.io.git
git branch -M main
git add --all
git commit -m "initial commit"
git push -u origin main